ResetSetup1()
{
	Setup("Chonkoppo",
		"Phaser Duck",
		"Phaser Duck",
		"Stork",
		"Crikeydile",
		"Crikeydile",
		"Blaken Gold",
		"Blaken Gold",
		"Blaken Gold",
		"Blaken Gold",
		"Blaken Gold",
		"Blaken Gold",
		"Blaken Gold",
		"Blaken Gold",
		"Blaken Gold",
		"Blaken Gold",
		"Blaken Gold",
		"Retiarius",)
}

ResetSetup2()
{
	Setup(
		"Little Piggy",
		"Boar",
		"Hippo",
		"Chromar",
		"Devilar",
		"Horn Hippo",
		"Beeg Hippo",
		"Gemmar",
		"Jekyllar",
		"Mammoth",
		"Iceular",
		"Rainboppo",
		"Hippemo",
		"Tarantuppo",
		"Chonkoppo",
		
		"Pet Rock",
		"Moutain",
		"Asteroid",
		"Snowy Peak",
		"Volcano",
		"Jupeter",
		"Astralis",
		"Glaciar",
		"Everest",
		"Pompeille",
		"Meltor",
		"Gasseon",
		"Orbiteer",
		"Martianus",
		"Luminavi",
		
		"Baby Egg",
		"Lil Chicken",
		"Lizard",
		"Duck",
		"Goose",
		"Crocodile",
		"Iguana",
		"Phaser Duck",
		"Cinderduck",
		"Stork",
		"Echo Delta",
		"Crikeydile",
		"Eggligator",
		"Purpback",
		"Blaken Gold",
		
		"Ogre Spawn",
		"Gobbo",
		"Ogre",
		"Orc",
		"Lizardman",
		"Ogre Giant",
		"Flesh Ogre",
		"Bulwark Orc",
		"Tundra Orc",
		"Lizardman",
		"Retiarius",
		"Hugh Mungus",
		"Musculor",
		"Corruptor",
		"Big Bone",
		
		"Torchy",
		
		"Crikeydile",
		"Purpback",
		"Purpback",
		"Purpback",
		"Purpback",
		"Purpback",
		"Purpback",
		"Purpback",
		"Purpback",
		"Purpback",
		"Purpback",
		"Purpback",
		"Purpback",
		"Purpback",
		"Purpback",
		"Purpback",
		
		"Blaken Gold", ; To remove when upgrades maxxed
		"Blaken Gold",
		"Blaken Gold",
		"Blaken Gold",
		"Blaken Gold",
		"Blaken Gold",
		; "Blaken Gold",
		; "Blaken Gold",
		; "Blaken Gold",
		; "Blaken Gold",
		; "Blaken Gold",
		; "Blaken Gold",
		; "Blaken Gold",
		; "Blaken Gold",
		; "Blaken Gold",
		
		"Musculor",
		
		"Goose",
		"Goose",
		"Goose",
		"Goose",
		"Goose",
		"Goose",
		"Goose",
		"Goose",
		"Goose",
		"Goose",
		"Goose",
		"Goose",
		"Goose",
		
		"Martianus",
		"Martianus",
		"Martianus",
		"Martianus",
		"Martianus",
		"Martianus",
		"Martianus",
		"Martianus",
		"Martianus",
		"Martianus",
		"Martianus",
		"Martianus",
		"Martianus",
		"Martianus",
		"Martianus",
		
		"Corruptor",
		"Corruptor",
		"Corruptor",
		"Corruptor",
		"Corruptor",
		"Corruptor",
		"Corruptor",
		"Corruptor",
		"Corruptor",
		"Corruptor",
		"Corruptor",
		"Corruptor",
		"Corruptor",
		"Corruptor",
		"Corruptor",
	)
}